name: Deploy to AWS

# トリガー条件
# このワークフローは、mainブランチにマージ(変更がプッシュ)されたときに実行されます。
on:
  push:
    branches: ["main"]

# 環境変数の設定
# 必要な情報を環境変数として指定。
# (ハンズオンでは、AWSリージョン、リポジトリ名、クラスター、サービス名、タスク定義ファイル名などの順次追加していきます)
env:
  AWS_REGION: ap-northeast-1
  ECR_REPOSITORY: testrepo

# ジョブの構成
# deployという名前のジョブを設定し、Ubuntu環境でGitHub Actionsを実行します。
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      # リポジトリのチェックアウト
      # actions/checkoutを使用して、GitHubリポジトリの内容をクローン。
      - name: Checkout
        uses: actions/checkout@v4

      # AWS認証情報の設定
      # aws-actions/configure-aws-credentialsを使用して、Githubのシークレットに保存したAWSアクセスキーとシークレットキーを用いて認証。
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # ECRへのログイン
      # aws-actions/amazon-ecr-loginを使用して、Amazon ECRにログイン。
      # (このステップで取得したレジストリ情報は後続のステップで使用されます)
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # Dockerイメージのビルドとプッシュ
      # docker buildコマンドでDockerイメージをビルドし、ECRリポジトリにプッシュ。
      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build --no-cache -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
