name: Deploy to Amazon ECS

on:
  workflow_call:
    inputs:
      aws-region:
        description: "リージョン"
        required: true
        type: string
      ecr-repository:
        description: "ECRリポジトリ"
        required: true
        type: string
      aws-service:
        description: "サービス名"
        required: true
        type: string
      aws-cluster:
        description: "クラスタ名"
        required: true
        type: string
      aws-task-definition:
        description: "タスク定義ファイル"
        required: true
        type: string
      container-name:
        description: "コンテナ名"
        required: true
        type: string

jobs:
  deploy:
    name: Deploy to ECS
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ inputs.aws-region }}
      ECR_REPOSITORY: ${{ inputs.ecr-repository }}
      ECS_SERVICE: ${{ inputs.aws-service }}
      ECS_CLUSTER: ${{ inputs.aws-cluster }}
      ECS_TASK_DEFINITION: ${{ inputs.aws-task-definition }}
      CONTAINER_NAME: ${{ inputs.container-name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build --no-cache -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Render Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ env.ECS_TASK_DEFINITION }}
          container-name: ${{ env.CONTAINER_NAME }}
          image: ${{ steps.build-image.outputs.image }}

      - name: Deploy to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true
          enable-ecs-managed-tags: true
          propagate-tags: SERVICE
