name: Deploy to DEV (AWS)

on:
  push:
    branches: ["main"]

jobs:
  deploy-dev:
    uses: ./.github/workflows/deploy.yml
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    with:
      aws-region: ap-northeast-1
      ecr-repository: frontend
      aws-service: test-service
      aws-cluster: frontend-cluster
      aws-task-definition: deploy/task-definition.json
      container-name: frontend-container
